# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Thomas Frenkiel | SEO & Marketing Strategy"
email: # Add your email if you'd like it public
description: >- # this means to ignore newlines until "baseurl:"
  Marketing and SEO strategist based in Stockholm, Sweden. Specializing in B2B marketing,
  web product management, and digital growth strategies. Currently leading SEO initiatives at Funnel.
baseurl: "" # the subpath of your site
url: "https://thomasfrenkiel.com" # your domain from CNAME
linkedin_username: thomasfrenkiel
# twitter_username: your_twitter_handle # Uncomment and add if you want to include Twitter
github_username: # Add if you want to include GitHub

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Adding SEO tag plugin for better meta tags

# SEO settings
lang: en
author: Thomas Frenkiel
social:
  name: Thomas Frenkiel
  links:
    - https://www.linkedin.com/in/thomasfrenkiel/
    # Add other social profile links as needed

# Site settings
timezone: Europe/Stockholm
show_excerpts: true # This will show blog post excerpts on the home page

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .DS_Store
